server:
  port: 1111


spring:
  application:
    name: Api-Gateway


  cloud:
    gateway:
      routes:
      - id: welcome-api
        uri: lb://STUDENT
        predicates:
        - Path=/student/**
        filters:
        - AuthenticationFilter        
      - id: greet-api
        uri: lb://TEACHER-SERVICE
        predicates:
        - Path=/teacher/**
        filters:
        - AuthenticationFilter      
      - id: authentication-api
        uri: lb://AUTH-SERVICE
        predicates:
        - Path=/auth/**
        
  main:
    web-application-type: reactive